theme = "jellybeans"

[editor]
line-number = "relative"
bufferline = "never"
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "‚ñè"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = false

# -----------------------------
# KEYBINDS
# -----------------------------

[keys.normal."space"]
F = "file_picker"
f = "file_picker_in_current_directory"
# e = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker.sh open'"
e = [ ":write-all", ":new", ":sh '~/.config/helix/yazi-picker.sh open'", ":buffer-close!", ":redraw", ":reload-all" ]
g = [ ":write-all", ":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all" ]

[keys.normal]
x = "select_line_below"
X = "select_line_above"
D = "kill_to_line_end"
Y =   ["select_mode", "goto_line_end", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
esc = ["collapse_selection",  "keep_primary_selection"]
C-j = [ "extend_to_line_bounds",  "delete_selection",  "paste_after" ]
C-k = [ "extend_to_line_bounds",  "delete_selection",  "move_line_up",  "paste_before" ]
